### PR TITLE
Increment version to 1.3.12

### PR DESCRIPTION
**Pull request by Divyaasm**
### Description

Version Bump from 1.3.11 to 1.3.12
### Issues Resolved

[List any issues this PR will resolve]

### Check List

- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
- [ ] Commits are signed per the DCO using `--signoff`

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by Divyaasm** [comment]
Not sure if the version number at [line](https://github.com/opensearch-project/anomaly-detection-dashboards-plugin/blob/87c230ef21c5f7eaf91e13944b3e2bb681ec8f4e/package.json#L7C8-L7C8) needs to be incremented as well.
 @prudhvigodithi

**Comment by gaiksaya** [comment]
> Not sure if the version number at [line](https://github.com/opensearch-project/anomaly-detection-dashboards-plugin/blob/87c230ef21c5f7eaf91e13944b3e2bb681ec8f4e/package.json#L7C8-L7C8) needs to be incremented as well. @prudhvigodithi @gaiksaya

Checked 2.x and main, it needs to be incremented

**Comment by prudhvigodithi** [comment]
Hey @ohltyler and @amitgalitz can you please check with `node` incompatible error? This error is causing issues to automation in raising the version increment PR's for anomaly-detection-dashboards-plugin repo.
@bbarani @peterzhuamazon 
Thank you

**Comment by ohltyler** [comment]
The complaining dependency was added in a CVE fix: https://github.com/opensearch-project/anomaly-detection-dashboards-plugin/pull/567/files

**Comment by gaiksaya** [comment]
> The complaining dependency `expect@29.6.1` was added in a CVE fix: https://github.com/opensearch-project/anomaly-detection-dashboards-plugin/pull/567/files, same error seen there.

Looks like that PR was merged with failing CI. Is it expected to fail or will this be an issue when we build distribution too?

**Comment by amitgalitz** [comment]
> > The complaining dependency `expect@29.6.1` was added in a CVE fix: https://github.com/opensearch-project/anomaly-detection-dashboards-plugin/pull/567/files, same error seen there.
> 
> Looks like that PR was merged with failing CI. Is it expected to fail or will this be an issue when we build distribution too?

Yeah it should be passing, I see some weird conflicts that I had to resolve in the dependency, I will open a working PR while I continue looking at the exact root cause

**Comment by ohltyler** [comment]
Closing in favor of #582

**Pull request closed without merging**
