### PR TITLE
Bumped semver to latest legacy version

### PR DESCRIPTION
**Pull request by VijayanB**
### Description

Bumped semver versions to address dependabot alerts.

### Check List

- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
- [ ] Commits are signed per the DCO using `--signoff`

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by VijayanB** [comment]
```
1. Add semver to resolutions 
2. Delete yarn.lock
3. run  yarn osd bootstrap to regenerate yarn.lock file
```

**Comment by kaituo** [comment]
added backport to 1.3 tag. Hopefully the workflow will succeed @VijayanB

**Comment by VijayanB** [comment]
@kaituo looks like issue from AD backend plugin. Is anyone working on that?

**Comment by kaituo** [comment]
@VijayanB Will prepare a PR to fix backend.

**Review by kaituo — APPROVED** [review]

**Review by ohltyler — APPROVED** [review]

**Comment by ohltyler** [comment]
Thanks for updating!

**Pull request merged**
