### PR TITLE
merge feature/mds branch into main

### PR DESCRIPTION
**Pull request by jackiehanyang**
### Description

This pr merges feature branch `feature/mds` into main.
It includes the following reviewed PRs:
- https://github.com/opensearch-project/anomaly-detection-dashboards-plugin/pull/722
- https://github.com/opensearch-project/anomaly-detection-dashboards-plugin/pull/728
- https://github.com/opensearch-project/anomaly-detection-dashboards-plugin/pull/732
- https://github.com/opensearch-project/anomaly-detection-dashboards-plugin/pull/734

### Issues Resolved

https://github.com/opensearch-project/anomaly-detection-dashboards-plugin/issues/721

### Check List

- [x] New functionality includes testing.
  - [x] All tests pass
- [ ] New functionality has been documented.
- [x] Commits are signed per the DCO using `--signoff`

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by huyaboo — APPROVED** [review]
Non blocking comment: Could we add UT in the case that MDS is enabled? Perhaps cut an issue to track this

**Review by dbwiddis — DISMISSED** [review]

**Review by amitgalitz — DISMISSED** [review]

**Comment by owaiskazi19** [comment]
DCO check is failing and the tests too. Can we fix that before merging this one @jackiehanyang ?

**Review by owaiskazi19 — CHANGES_REQUESTED** [review]
DCO check is failing and the tests too. Can we fix that before merging this one @jackiehanyang ?

**Comment by jackiehanyang** [comment]
> Non blocking comment: Could we add UT in the case that MDS is enabled? Perhaps cut an issue to track this

Planning to cover MDS is enabled case in integ test. Every page renders the same even MDS is enabled, so I didn't add new test cases.

**Comment by jackiehanyang** [comment]
DCO is failing because this pr is triggered by using github UI. Every feature branch pr mentioned in this pr has been code reviewed and used `--signoff` signature.

**Comment by jackiehanyang** [comment]
> DCO is failing because this pr is triggered by using github UI. Every feature branch pr mentioned in this pr has been code reviewed and used `--signoff` signature.

Confirmed  that some graphical user interfaces (GUIs) for Git might not directly support adding a sign-off.
Did manual signoff. Now DCO is passing

**Pull request closed without merging**
