### PR TITLE
feat: allow date_nanos dates in timestamp selection

### PR DESCRIPTION
**Pull request by jehuty0shift**
### Description

This change is enabling the selection of **date_nanos** date type for creating detectors in the plugin. The feature has been merged on the plugin side 
https://github.com/opensearch-project/anomaly-detection/pull/1238 and is being backported to 2.X : 
https://github.com/opensearch-project/anomaly-detection/pull/1249

The change add the **date_nanos** dataType and enable its selection as a date field. 

I could test the change by cherry-picking this commit this code to 2.14 branch and testing OpenSearch Dashboard against a cluster with the patched anomaly-detection plugin (to pass validation on date_nanos). 

The mapping of the timestamp field is the following 

```
        "timestamp" : {
          "type" : "date_nanos",
          "format" : "epoch_millis||yyyy-MM-dd HH:mm:ss.SSS||yyyy-MM-dd HH:mm:ss.SSSSSS||yyyy-MM-dd HH:mm:ss.n"
        },
```

Attached are the screenshot showing the field appearing in the date fields listing and the final detector validated. The last screenshot shows an historical analysis working as intended.  

pr-1
pr-2
pr-3

### Issues Resolved
No issues have been opened on this project. 

### Check List

- [x] New functionality includes testing.
- [ ] All tests pass
- [ ] New functionality has been documented.
- [X] Commits are signed per the DCO using `--signoff`

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by jehuty0shift** [comment]
I couldn't run all tests on my laptop (out of RAM), I'm ready to contribute to this PR by writing some unit test if needed, but i would need an example to replicate (i am not at all proficient in javascript/typescript).  I don't know if documentation must be updated to reflect this change since it doesn't indicate the limitation in the first place.

**Comment by kaituo** [comment]
> I couldn't run all tests on my laptop (out of RAM), I'm ready to contribute to this PR by writing some unit test if needed, but i would need an example to replicate (i am not at all proficient in javascript/typescript). I don't know if documentation must be updated to reflect this change since it doesn't indicate the limitation in the first place.

You can use https://github.com/opensearch-project/anomaly-detection-dashboards-plugin/blob/main/public/pages/DefineDetector/components/Datasource/__tests__/IndexOption.test.tsx as an example. Once you finished, I can help run all tests in github CI.

**Comment by kaituo** [comment]
Please rebase from main as I fixed CI https://github.com/opensearch-project/anomaly-detection-dashboards-plugin/pull/798

**Comment by kaituo** [comment]
Can you list what manual tests you have done in the Description part?

**Comment by jehuty0shift** [comment]
I added some text and screenshot, let me know if you need something more.

**Review by kaituo — APPROVED** [review]

**Pull request merged**
