### PR TITLE
Bump version to 1.2

### PR DESCRIPTION
**Pull request by ohltyler**
Signed-off-by: Tyler Ohlsen <ohltyler@amazon.com>

### Description

This PR bumps the plugin version to 1.2.0.0, & compatibility with Dashboards 1.2.0.

Also removes the legacy CD workflow. Plugin will now be built by adding it into the respective [manifest files in the opensearch-build repo](https://github.com/opensearch-project/opensearch-build/tree/main/manifests) during the release cycle.

Doesn't touch CI workflow - that's being investigated separately.

NOTE: haven't sanity tested since AD backend plugin hasn't version bumped. Will do that when available. Obviously won't merge until the backend changes are done.

### Check List
- [x] Commits are signed per the DCO using `--signoff`

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by amitgalitz** [comment]
Since we are removing current CD, is plan to add CD with maven later on?

**Comment by ohltyler** [comment]
> Since we are removing current CD, is plan to add CD with maven later on?

CI will be with maven. CD is deprecated, since the infra build process is different now and uses manifest files

**Comment by ylwu-amzn** [comment]
Should we fix the E2E test workflow failure?

**Review by ylwu-amzn — APPROVED** [review]

**Comment by ylwu-amzn** [comment]
> Should we fix the E2E test workflow failure?

@amitgalitz is working on fixing E2E test workflow, approved this 1.2 bumping PR.

**Review by amitgalitz — APPROVED** [review]

**Pull request merged**
