### PR TITLE
bumping main to 3.0

### PR DESCRIPTION
**Pull request by amitgalitz**
Signed-off-by: Amit Galitzky <amgalitz@amazon.com>

### Description

bumping main to 3.0 branch

### Issues Resolved

https://github.com/opensearch-project/anomaly-detection-dashboards-plugin/issues/290

### Check List
- [x] Commits are signed per the DCO using `--signoff`

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by ohltyler — APPROVED** [review]

**Comment by amitgalitz** [comment]
Remote integ tests are flaky here: 
Run 1: 3 of 8 test suites had failures
Run 2 :  4 of 8 test suites had failures
Run 3: It couldn't find job-scheduler 3.0.0 zip even though it was found for previous 2 runs

**Comment by amitgalitz** [comment]
Job scheduler is currently failing for 3.x so we can't successfully run CI here: https://github.com/opensearch-project/job-scheduler/issues/249
On a side note: In my opinion we really should be careful how much time we decide to spend to get main stable cause if we are constantly having breaking changes from core and other dependencies it can create a constant loop of maintenance that will slow down our development speed.

**Comment by ohltyler** [comment]
> 

I think it's worth keeping an eye out on the amount of effort needed to remain compatible with the next major version / 3.0. The main idea is that it's supposed to be the 'cutting edge' branch that will have all of the newest changes in it, and it eases the amount of effort we will have to make during a 3.0 release since we will have already done the work to be compatible with it based on all of the breaking changes in it as they are merged. But 3.0 shouldn't consistently break - if so, it's worth further discussion and probably opening a ticket in  https://github.com/opensearch-project/opensearch-plugins

**Comment by ohltyler** [comment]
@amitgalitz actually looks like there's a good thread about this here: https://github.com/opensearch-project/opensearch-plugins/issues/142#issuecomment-1289727536

**Comment by amitgalitz** [comment]
The remote tests have been extra flaky on this PR. The create AD test suite is failing more consistently with this error: `Expected to find element: [data-test-subj="defineOrEditDetectorTitle"], but never found it.`
Looking into it currently but locally every single integ is failing for me, probably something I missed in my set up with the version bump but if not, I'll open an issue in FTRepo.

**Comment by amitgalitz** [comment]
@jackiehanyang could the failure on windows-ci PR be related to this not being merged yet?

**Comment by ohltyler** [comment]
@jackiehanyang can we merge this? Sounds like CI failures are going to be fixed with #330?

**Comment by jackiehanyang** [comment]
> @jackiehanyang can we merge this? Sounds like CI failures are going to be fixed with #330?

no I don't think the CI failure will be fixed with https://github.com/opensearch-project/anomaly-detection-dashboards-plugin/pull/330, the CI failure looks like related to 3.0 specifically. Also let's 2.4 windows pr merged before this since it has a higher priority

**Comment by jackiehanyang** [comment]
looked into the error message for failed remote integ tests workflow. It's failing due to flaky integ tests, nothing related to 3.0 specific issue. So it's good to merge @ohltyler

**Review by jackiehanyang — APPROVED** [review]

**Comment by ohltyler** [comment]
@jackiehanyang fyi, because I linked the issue, it would have closed automatically when merging :)

**Pull request merged**
